# 1. Download the source code
vcpkg_download_distfile(
    ARCHIVE
    URLS "https://github.com/microsoft/onnxruntime/releases/download/v1.23.1/onnxruntime-source-1.23.1.tgz"
    FILENAME "onnxruntime-source-1.23.1.tgz"
    SHA512 e4e101a93864197e7428f522810a08e178122d645511b0e35233157e841f4f89d3630f9a744274c3e80f2d4f2601c38e9c91d4e0b04a11f211516e8b4e339b35
)

# 2. Extract the downloaded archive.
vcpkg_extract_source_archive(
    SOURCE_PATH
    ARCHIVE "${ARCHIVE}"
)

# 3. Configure build options based on features
set(ONNXRUNTIME_BUILD_OPTIONS "")
if("static-cpu" IN_LIST FEATURES)
    list(APPEND ONNXRUNTIME_BUILD_OPTIONS
        --config Release
        --parallel
        --skip_tests
        --skip_submodule_sync
        --cmake_extra_defines "onnxruntime_USE_OPENMP=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON"
    )
else()
    message(FATAL_ERROR "This onnxruntime port currently only supports the 'static-cpu' feature.")
endif()

# 4. Run the build script
vcpkg_execute_build_process(
    COMMAND ${BASH} "${SOURCE_PATH}/build.sh" ${ONNXRUNTIME_BUILD_OPTIONS}
    WORKING_DIRECTORY "${SOURCE_PATH}"
    LOGNAME build-onnxruntime-script
)

# 5. Manually copy the build results.
file(INSTALL "${SOURCE_PATH}/include/" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(GLOB STATIC_LIBS "${SOURCE_PATH}/build/Linux/Release/*.a")
file(INSTALL ${STATIC_LIBS} DESTINATION "${CURRENT_PACKAGES_DIR}/lib")

# 6. [FIX] Manually copy ALL CMake config files.
#    This uses a wildcard to ensure we grab Config, Targets,
#    and any other .cmake files generated by the build.
file(GLOB CMAKE_FILES
    "${SOURCE_PATH}/build/Linux/Release/onnxruntime*.cmake"
)

# Install them to the location vcpkg expects
file(INSTALL ${CMAKE_FILES}
     DESTINATION "${CURRENT_PACKAGES_DIR}/share/onnxruntime"
)

# 7. Final cleanup.
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
