# 1. Download the source code
vcpkg_download_distfile(
    ARCHIVE
    URLS "https://github.com/microsoft/onnxruntime/archive/refs/tags/v1.23.1.tar.gz"
    FILENAME "onnxruntime-v1.23.1.tar.gz"
    # NOTE: You need to replace this with the correct hash.
    SHA512 fcb4b786a503a24868efe608c02f072b762537891d91ac4d8ec995fe726964c284d685dc68ffda28e86d03c03cac2e9f0de6a1e8d2efc1c44d2c01c15a4588ae
)

# 2. Extract the downloaded archive.
vcpkg_extract_source_archive(
    SOURCE_PATH
    ARCHIVE "${ARCHIVE}"
)

# 3. Run the build script
vcpkg_execute_build_process(
    COMMAND ${BASH} "${SOURCE_PATH}/build.sh"
        --config Release
        --parallel
        --skip_tests
        --skip_submodule_sync
        --cmake_extra_defines "onnxruntime_USE_OPENMP=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON"
    WORKING_DIRECTORY "${SOURCE_PATH}"
    LOGNAME build-onnxruntime-script
)

# 4. Manually copy the build results.
file(INSTALL "${SOURCE_PATH}/include/" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(GLOB STATIC_LIBS "${SOURCE_PATH}/build/Linux/Release/*.a")
file(INSTALL ${STATIC_LIBS} DESTINATION "${CURRENT_PACKAGES_DIR}/lib")

# 5. [FIX] Manually copy ALL CMake config files.
#    This uses a wildcard to ensure we grab Config, Targets,
#    and any other .cmake files generated by the build.
file(GLOB CMAKE_FILES
    "${SOURCE_PATH}/build/Linux/Release/onnxruntime*.cmake"
)

# Install them to the location vcpkg expects
file(INSTALL ${CMAKE_FILES}
     DESTINATION "${CURRENT_PACKAGES_DIR}/share/onnxruntime"
)

# 6. Final cleanup.
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)